In [10]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [11]:
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df['target'] = iris.target

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [12]:
df = df[df['target'] != 0][['sepal width (cm)', 'petal length (cm)', 'target']]

In [13]:
df.head()

    sepal width (cm)  petal length (cm)  target
50               3.2                4.7       1
51               3.2                4.5       1
52               3.1                4.9       1
53               2.3                4.0       1
54               2.8                4.6       1

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt